# yaml-language-server: $schema=https://www.schemastore.org/pnpm-workspace.json

packages:
  # include app packages so they can consume local workspace packages
  - "apps/*"
  # all packages in direct subdirs of packages/
  - "packages/*"
